# Generated by Django 4.2.6 on 2023-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('views_count', models.IntegerField(default=0, verbose_name='number of views')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'post`s',
                'ordering': ('-date_of_creation',),
            },
        ),
    ]
